config: workaround to fix the wrong xml config
which causes the following build failure:

Traceback (most recent call last):
  File "/home/hc/office/xuantie/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/validator.py", line 309, in <module>
    main(args)
  File "/home/hc/office/xuantie/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/validator.py", line 288, in main
    nr_all_errors = validate_one(validation_pipeline, obj, args.board, args.scenario)
  File "/home/hc/office/xuantie/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/validator.py", line 236, in validate_one
    validation_pipeline.run(pipeline_obj)
  File "/home/hc/office/xuantie/acrn-hypervisor/misc/config_tools/scenario_config/pipeline.py", line 68, in run
    stage.run(obj)
  File "/home/hc/office/xuantie/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/validator.py", line 209, in run
    errors = obj.get("validator").check_semantics(obj.get("board_etree"), obj.get("scenario_etree"))
  File "/home/hc/office/xuantie/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/validator.py", line 97, in check_semantics
    e = self.format_error(unified_node, parent_map, error)
  File "/home/hc/office/xuantie/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/validator.py", line 150, in format_error
    counter_example = ScenarioValidator.get_counter_example(error)
  File "/home/hc/office/xuantie/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/validator.py", line 130, in get_counter_example
    result = assertion.token.evaluate(context)
  File "/home/hc/.local/lib/python3.6/site-packages/elementpath/xpath1/xpath1_operators.py", line 433, in evaluate_comparison_operators
    raise self.error('XPTY0004', err) from None
elementpath.exceptions.ElementPathTypeError: '>' operator at line 1, column 37: [err:XPTY0004] cannot apply fn:sum() to string-based types

Signed-off-by: Haicheng Li <haicheng.li@outlook.com>